In [1]:
import pandas as pd

## Exploring Rotten Tomatoes and IMDB Data Sets for Insights

Hello there!

In this notebook file, I will be taking a look at IMDB and Rotten Tomatos data sets sourced from the web.

For my initial analysis of the movies data sets, I first plan on doing an initial scan of a couple of different data sets that were provided in our /zippedData project folder. I want to see what types of data we are working with and if there are any notable columns or inconsistencies in the sets.

In [17]:
basics = pd.read_csv('imdb.title.basics.csv.gz')

In [4]:
basics.head()

tconst                    primary_title              original_title  \
0  tt0063540                        Sunghursh                   Sunghursh   
1  tt0066787  One Day Before the Rainy Season             Ashad Ka Ek Din   
2  tt0069049       The Other Side of the Wind  The Other Side of the Wind   
3  tt0069204                  Sabse Bada Sukh             Sabse Bada Sukh   
4  tt0100275         The Wandering Soap Opera       La Telenovela Errante   

   start_year  runtime_minutes                genres  
0        2013            175.0    Action,Crime,Drama  
1        2019            114.0       Biography,Drama  
2        2018            122.0                 Drama  
3        2018              NaN          Comedy,Drama  
4        2017             80.0  Comedy,Drama,Fantasy

The IMDB data looks pretty straightforward, and nice and clean. Although, one of my responsibilities for my team is to explore insights regarding the ratings and reviews of movies. I think I want to take a look at the Rotten Tomatoes data and see if anything interesting sticks out.

In [2]:
rotten = pd.read_csv('rt.movie_info.tsv.gz', delimiter="\t")
#initialized a dataframe to access a database containing rotten tomatos reviews

In [3]:
rotten.head(20)

id                                           synopsis rating  \
0    1  This gritty, fast-paced, and innovative police...      R   
1    3  New York City, not-too-distant-future: Eric Pa...      R   
2    5  Illeana Douglas delivers a superb performance ...      R   
3    6  Michael Douglas runs afoul of a treacherous su...      R   
4    7                                                NaN     NR   
5    8  The year is 1942. As the Allies unite overseas...     PG   
6   10  Some cast and crew from NBC's highly acclaimed...  PG-13   
7   13  Stewart Kane, an Irishman living in the Austra...      R   
8   14  "Love Ranch" is a bittersweet love story that ...      R   
9   15  When a diamond expedition in the Congo is lost...  PG-13   
10  17                                                NaN    NaN   
11  18  In 1979, Bill Viola and Frank Caliguri dreamed...     NR   
12  19  While Microsoft may be the biggest software co...     NR   
13  20  Rachel (Britt Ekland) is an Amish girl who rej...  PG-13   
14  21  Old-school comic Rodney "I get no respect" Dan...      R   
15  22  Two-time Academy Award Winner Kevin Spacey giv...      R   
16  23  A fictional film set in the alluring world of ...      R   
17  24  Three young boys discover a stranded Russian s...     PG   
18  25  From ancient Japan's most enduring tale, the e...  PG-13   
19  26  A comic series of short vignettes build on one...      R   

                                                genre             director  \
0                 Action and Adventure|Classics|Drama     William Friedkin   
1                   Drama|Science Fiction and Fantasy     David Cronenberg   
2                   Drama|Musical and Performing Arts       Allison Anders   
3                          Drama|Mystery and Suspense       Barry Levinson   
4                                       Drama|Romance       Rodney Bennett   
5                               Drama|Kids and Family          Jay Russell   
6                                              Comedy          Jake Kasdan   
7                                               Drama         Ray Lawrence   
8                                               Drama      Taylor Hackford   
9   Action and Adventure|Mystery and Suspense|Scie...       Frank Marshall   
10                                                NaN                  NaN   
11                                        Documentary                  NaN   
12                       Documentary|Special Interest                  NaN   
13                              Classics|Comedy|Drama     William Friedkin   
14                                             Comedy        Peter Baldwin   
15                  Comedy|Drama|Mystery and Suspense  George Hickenlooper   
16                                              Drama                  NaN   
17                  Action and Adventure|Comedy|Drama       Rick Rosenthal   
18  Action and Adventure|Drama|Science Fiction and...     Carl Erik Rinsch   
19  Art House and International|Comedy|Drama|Music...         Jim Jarmusch   

                                               writer  theater_date  \
0                                      Ernest Tidyman   Oct 9, 1971   
1                        David Cronenberg|Don DeLillo  Aug 17, 2012   
2                                      Allison Anders  Sep 13, 1996   
3                     Paul Attanasio|Michael Crichton   Dec 9, 1994   
4                                        Giles Cooper           NaN   
5                                     Gail Gilchriest   Mar 3, 2000   
6                                          Mike White  Jan 11, 2002   
7                    Raymond Carver|Beatrix Christian  Apr 27, 2006   
8                                       Mark Jacobson  Jun 30, 2010   
9                                John Patrick Shanley   Jun 9, 1995   
10                                                NaN           NaN   
11                                       Robert Zullo           NaN   
12           

In [12]:
!ls

MovieAnalysis-Samantha.ipynb
Untitled.ipynb
bom.movie_gross.csv.gz
imdb.name.basics.csv.gz
imdb.title.akas.csv.gz
imdb.title.basics.csv.gz
imdb.title.crew.csv.gz
imdb.title.principals.csv.gz
imdb.title.ratings.csv.gz
rt.movie_info.tsv.gz
rt.reviews.tsv.gz
tmdb.movies.csv.gz
tn.movie_budgets.csv.gz


In [14]:
# Gathering information about Microsoft company values: https://www.microsoft.com/en-us/about/values
# Mission in action: Innovation, Diversity and Inclusion, Corporate Social Responsibility, AI, Trustworthy Computing, COVID-19 safety
# Values: Respect, Integrity, Accountability

In [37]:
type(rotten)

pandas.core.frame.DataFrame

In [38]:
rotten.info()
# we can see a lot of missing values are present... box office data seems missing from the majority of reviews, so we will
# probably just use this data set to get an idea of sentiment and not necessarily sales stats

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            1560 non-null   int64 
 1   synopsis      1498 non-null   object
 2   rating        1557 non-null   object
 3   genre         1552 non-null   object
 4   director      1361 non-null   object
 5   writer        1111 non-null   object
 6   theater_date  1201 non-null   object
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    object
 10  runtime       1530 non-null   object
 11  studio        494 non-null    object
dtypes: int64(1), object(11)
memory usage: 146.4+ KB


In [39]:
rotten.index
# determine amount of reviews contained in extracted data set, 1560 reviews

RangeIndex(start=0, stop=1560, step=1)

In [40]:
rotten['rating']

0        R
1        R
2        R
3        R
4       NR
        ..
1555     R
1556    PG
1557     G
1558    PG
1559     R
Name: rating, Length: 1560, dtype: object

In [41]:
rotten.describe()

id
count  1560.000000
mean   1007.303846
std     579.164527
min       1.000000
25%     504.750000
50%    1007.500000
75%    1503.250000
max    2000.000000

In [42]:
rotten['genre'].unique()

array(['Action and Adventure|Classics|Drama',
       'Drama|Science Fiction and Fantasy',
       'Drama|Musical and Performing Arts', 'Drama|Mystery and Suspense',
       'Drama|Romance', 'Drama|Kids and Family', 'Comedy', 'Drama',
       'Action and Adventure|Mystery and Suspense|Science Fiction and Fantasy',
       nan, 'Documentary', 'Documentary|Special Interest',
       'Classics|Comedy|Drama', 'Comedy|Drama|Mystery and Suspense',
       'Action and Adventure|Comedy|Drama',
       'Action and Adventure|Drama|Science Fiction and Fantasy',
       'Art House and International|Comedy|Drama|Musical and Performing Arts',
       'Musical and Performing Arts',
       'Classics|Comedy|Musical and Performing Arts|Romance',
       'Action and Adventure|Drama|Mystery and Suspense',
       'Action and Adventure|Mystery and Suspense',
       'Art House and International|Classics|Horror|Mystery and Suspense',
       'Horror',
       'Action and Adventure|Classics|Drama|Mystery and Suspense',
   

In [24]:
#Lots of entries have several genres assigned to the movie being reviewed

In [26]:
#want to determine somehow how to gain information about the RT rating for these reviews...

In [43]:
rotten.keys()

Index(['id', 'synopsis', 'rating', 'genre', 'director', 'writer',
       'theater_date', 'dvd_date', 'currency', 'box_office', 'runtime',
       'studio'],
      dtype='object')

In [44]:
rotten['id']

0          1
1          3
2          5
3          6
4          7
        ... 
1555    1996
1556    1997
1557    1998
1558    1999
1559    2000
Name: id, Length: 1560, dtype: int64

In [29]:
#note: come back to this data set... might take a while to uncover whats happening here

In [32]:
#lets try looking at the RT movie data set and see if we can combine these... if not then try imbd

In [4]:
rtreviews = pd.read_csv('rt.reviews.tsv.gz', sep="\t", encoding='latin-1')

In [5]:
rtreviews.head(50)
#some reviews contain rating out of 5, others contain a letter grade

id                                             review rating   fresh  \
0    3  A distinctly gallows take on contemporary fina...    3/5   fresh   
1    3  It's an allegory in search of a meaning that n...    NaN  rotten   
2    3  ... life lived in a bubble in financial dealin...    NaN   fresh   
3    3  Continuing along a line introduced in last yea...    NaN   fresh   
4    3             ... a perverse twist on neorealism...     NaN   fresh   
5    3  ... Cronenberg's Cosmopolis expresses somethin...    NaN   fresh   
6    3  Quickly grows repetitive and tiresome, meander...      C  rotten   
7    3  Cronenberg is not a director to be daunted by ...    2/5  rotten   
8    3  Cronenberg's cold, exacting precision and emot...    NaN   fresh   
9    3  Over and above its topical urgency or the bit ...    NaN   fresh   
10   3  Cosmopolis" is a hypnotic examination of our m...    NaN   fresh   
11   3  While not one of Cronenberg's stronger films, ...     B-   fresh   
12   3  Robert Pattinson works mighty hard to make Cos...    2/4  rotten   
13   3  The anger over the injustice of the financial ...      B   fresh   
14   3  For those who like their Cronenberg thick and ...    3/4   fresh   
15   3  For better or worse - often both - Cosmopolis ...    3/5   fresh   
16   3  For one of the smartest films I've seen in a w...    4/5   fresh   
17   3      Its major problem is that it's not cinematic.      B   fresh   
18   3  It's fascinating to watch Pattinson actually a...    2/4  rotten   
19   3  A black comedy as dry and deadpan as a bleache...    4/4   fresh   
20   3  While 'Cosmopolis' is mostly emotionless and a...   6/10   fresh   
21   3  In the past, Cronenberg has used such deadpan ...    1/4  rotten   
22   3  ... a movie about a sentient zombie, trapped i...      8   fresh   
23   3  Those who said Don DeLillo's book was unfilmab...    2/5  rotten   
24   3  The rapid dialogue is dry and mannered, like a...  2.5/4  rotten   
25   3  Cosmopolis" is proof that a film can be provoc...   4/10  rotten   
26   3  It's fascinating but anti-cinematic and a frus...    NaN   fresh   
27   3  Throws heady ideas at you faster than Michael ...  2.5/4   fresh   
28   3  A master filmmaker's rumination on capitalism ...    NaN   fresh   
29   3  David Cronenberg takes a wayward shot at makin...  2.0/5  rotten   
30   3  Cynical and futile - a total waste of time and...   3/10  rotten   
31   3  If there has ever been a point in human histor...   7/10   fresh   
32   3  Well, if it isn't the most confounding movie o...    NaN  rotten   
33   3  If Cosmopolis remains chilly and remote, it do...    3/5   fresh   
34   3  I don't know if DeLillo's fetishized doubletal...      C  rotten   
35   3  Though hardly a crowd-pleaser. it's the sort o...     A-   fresh   
36   3  Cosmopolis deconstructs language, symbols and ...    4/5   fresh   
37   3  Cold and calculated, Cosmospolis is a mesmeriz...    NaN   fresh   
38   3  With a cast like this we expected major Cronen...    NaN   fresh   
39   3                                   Not worth seeing    NaN  rotten   
40   3  Cosmopolis is an investment that pays off enor...    5/5   fresh   
41   3  Cosmopolis is something like the anti-matter v...    NaN   fresh   
42   3  If you pay even a single penny to watch the th...      F  rotten   
43   3  I can't convince myself that Cosmopolis is any...  3.5/4   fresh   
44   3  I must admit Robert Pattinson does dead extrem...    3/5   fresh   
45   3  Cosmopolis" is a deeply subversive, deeply int...    4/4   fresh   
46   3  Robert Pattinson... brings a slick, knowing ro...    NaN   fresh   
47   3  It feels like each and every moment bursts for...    2/4  rotten   
48   3  Then there's the matter of the screenplay, whi...    2/4  rotten   
49   3  Art-house cinema at its most achingly smarmy a...    NaN  rotten   

                 critic  top_critic                        publisher  \
0            PJ Nabarro           0                  Pa

In [34]:
#my first guess is that we can link the rotten tomatos data frames by "id" where "id" is the movie with many reviews associated with it


In [5]:
movie5 = rtreviews[rtreviews['id'] == 5]

movie5

id                                             review rating   fresh  \
163   5  This is not the smoothest trip: the transition...    NaN   fresh   
164   5  Charming tale of songwriter finding her voice ...    4/5   fresh   
165   5  The lead, Ileana Douglas, is good, but the mus...     C+   fresh   
166   5  An intelligent, engaging comedy-drama that wil...  3.5/4   fresh   
167   5  Illeana Douglas grabs onto her first starring ...    NaN   fresh   
168   5  Pean to creativity and a celebration of one wo...    NaN   fresh   
169   5                                                NaN    3/5   fresh   
170   5                                                NaN    2/5  rotten   
171   5                                                NaN    3/5   fresh   
172   5                                                NaN    3/5   fresh   
173   5                                                NaN   6/10   fresh   
174   5                                                NaN    3/5   fresh   
175   5                                                NaN  3.5/4   fresh   
176   5                                                NaN    5/5   fresh   
177   5                                                NaN    5/5   fresh   
178   5                                                NaN  1.5/4  rotten   
179   5                                                NaN  2.5/4  rotten   
180   5                                                NaN  2.5/4  rotten   
181   5                                                NaN  3.5/4   fresh   
182   5                                                NaN    3/4   fresh   
183   5                                                NaN    2/4  rotten   
184   5                                                NaN  3.5/5   fresh   
185   5                                                NaN   7/10   fresh   

                  critic  top_critic                  publisher  \
163          David Ansen           1                   Newsweek   
164       Brian Costello           0         Common Sense Media   
165         Emanuel Levy           0            EmanuelLevy.Com   
166      Michael Dequina           0         TheMovieReport.com   
167        Frank Wilkins           0     ReelTalk Movie Reviews   
168                  NaN           0  Spirituality and Practice   
169         Cole Smithey           0            ColeSmithey.com   
170        Chuck O'Leary           0           Fantastica Daily   
171        Philip Martin           0  Arkansas Democrat-Gazette   
172           Eric Melin           0               Lawrence.com   
173       Dragan Antulov           0    rec.arts.movies.reviews   
174          Carol Cling           0   Las Vegas Review-Journal   
175       Jeanne Aufmuth           0           Palo Alto Weekly   
176         James Rocchi           0                    Netflix   
177      Rob Blackwelder           0                SPLICEDWire   
178                  NaN           1             Globe and Mail   
179   James Berardinelli           1                  ReelViews   
180          Roger Ebert           1          Chicago Sun-Times   
181   Madeleine Williams           0                 Cinematter   
182         Steve Rhodes           0           Internet Reviews   
183          Susan Stark           1               Detroit News   
184  Marjorie Baumgarten           0           Austin Chronicle   
185        Scott Renshaw           0    rec.arts.movies.reviews   

                   date  
163   February 26, 2018  
164       July 12, 2016  
165        June 7, 2011  
166  September 10, 2005  
167    December 3, 2003  
168     August 27, 2002  
169    October 10, 2005  
170     October 9, 2005  
171      April 28, 2005  
172     August 24, 2004  
173    November 5, 2003  
174     August 22, 2003  
175        May 14, 2003  
176    November 7, 2002  
177     August 21, 2002  
178      April 12, 2002  
179     January 1, 2000  
180     January 1, 2000  
181     January 1, 2000  
182     January 1, 2000  
1

In [39]:
rtreviews['id']
#looks like this is a collection of movies 3-2000?

0           3
1           3
2           3
3           3
4           3
         ... 
54427    2000
54428    2000
54429    2000
54430    2000
54431    2000
Name: id, Length: 54432, dtype: int64

In [8]:
!ls

MovieAnalysis-Samantha.ipynb
Untitled.ipynb
bom.movie_gross.csv.gz
imdb.name.basics.csv.gz
imdb.title.akas.csv.gz
imdb.title.basics.csv.gz
imdb.title.crew.csv.gz
imdb.title.principals.csv.gz
imdb.title.ratings.csv.gz
rt.movie_info.tsv.gz
rt.reviews.tsv.gz
tmdb.movies.csv.gz
tn.movie_budgets.csv.gz


It appears that the ID #3 in both my first and second Rotten Tomatoes dataframes mentions David Cronenberg. 
ID #5 mentions Ileana Douglas being the lead of the movie in both sets of data as well.

It is safe for me to assume that the ID # is the common key column in both Rotten Tomatoes sets of data. Therefore, I want to merge these so that I have a more thorough set of data to work with.

## A Quick Jump Back To IMDB's Reviews

Before I make the commitment to diving head first into the Rotten Tomatoes data, I realized that IMDB has its own separate "ratings" file which may be easier and cleaner to work with. I hope I can explore both, but I want to take a quick peek.

In [11]:
imdbreviews = pd.read_csv("imdb.title.ratings.csv.gz")

In [13]:
imdbreviews.head()

tconst  averagerating  numvotes
0  tt10356526            8.3        31
1  tt10384606            8.9       559
2   tt1042974            6.4        20
3   tt1043726            4.2     50352
4   tt1060240            6.5        21

In [14]:
#tconst could be the key that identifies all the movies and links them between the data sets

In [15]:
#so far, basics DF is "IMDB title basics", and imdbreviews DF is IMDB title ratings. 

In [22]:
#reminder of what the IMDB basics data set looks like, this is "title basics"
basics.head()

tconst                    primary_title              original_title  \
0  tt0063540                        Sunghursh                   Sunghursh   
1  tt0066787  One Day Before the Rainy Season             Ashad Ka Ek Din   
2  tt0069049       The Other Side of the Wind  The Other Side of the Wind   
3  tt0069204                  Sabse Bada Sukh             Sabse Bada Sukh   
4  tt0100275         The Wandering Soap Opera       La Telenovela Errante   

   start_year  runtime_minutes                genres  
0        2013            175.0    Action,Crime,Drama  
1        2019            114.0       Biography,Drama  
2        2018            122.0                 Drama  
3        2018              NaN          Comedy,Drama  
4        2017             80.0  Comedy,Drama,Fantasy

In [19]:
#looking at IMBD "name basics"
namebasics = pd.read_csv("imdb.name.basics.csv.gz")

In [20]:
namebasics.head()

nconst       primary_name  birth_year  death_year  \
0  nm0061671  Mary Ellen Bauder         NaN         NaN   
1  nm0061865       Joseph Bauer         NaN         NaN   
2  nm0062070         Bruce Baum         NaN         NaN   
3  nm0062195       Axel Baumann         NaN         NaN   
4  nm0062798        Pete Baxter         NaN         NaN   

                                 primary_profession  \
0         miscellaneous,production_manager,producer   
1        composer,music_department,sound_department   
2                        miscellaneous,actor,writer   
3  camera_department,cinematographer,art_department   
4  production_designer,art_department,set_decorator   

                          known_for_titles  
0  tt0837562,tt2398241,tt0844471,tt0118553  
1  tt0896534,tt6791238,tt0287072,tt1682940  
2  tt1470654,tt0363631,tt0104030,tt0102898  
3  tt0114371,tt2004304,tt1618448,tt1224387  
4  tt0452644,tt0452692,tt3458030,tt2178256

In [21]:
namebasics.keys()

Index(['nconst', 'primary_name', 'birth_year', 'death_year',
       'primary_profession', 'known_for_titles'],
      dtype='object')

In [26]:
titleakas = pd.read_csv('imdb.title.akas.csv.gz')
titleakas.head(20)

title_id  ordering                                    title region  \
0   tt0369610        10                            Джурасик свят     BG   
1   tt0369610        11                        Jurashikku warudo     JP   
2   tt0369610        12  Jurassic World: O Mundo dos Dinossauros     BR   
3   tt0369610        13                  O Mundo dos Dinossauros     BR   
4   tt0369610        14                           Jurassic World     FR   
5   tt0369610        15                           Jurassic World     GR   
6   tt0369610        16                           Jurassic World     IT   
7   tt0369610        17                            Jurski svijet     HR   
8   tt0369610        18                             Olam ha'Yura     IL   
9   tt0369610        19           Jurassic World: Mundo Jurásico     MX   
10  tt0369610         1          Jurassic World: Sauruste maailm     EE   
11  tt0369610        20                           Jurassic World     SE   
12  tt0369610        21                        Jurassic World 3D     US   
13  tt0369610        22                        Jurassic World 3D     DE   
14  tt0369610        23                        Jurassic World 3D    XWW   
15  tt0369610        24                   Juras laikmeta pasaule     LV   
16  tt0369610        25                          Mundo Jurássico     PT   
17  tt0369610        26                      Мир Юрского периода     RU   
18  tt0369610        27                              Jurský svět     CZ   
19  tt0369610        28                         Monde jurassique     CA   

   language        types   attributes  is_original_title  
0        bg          NaN          NaN                0.0  
1       NaN  imdbDisplay          NaN                0.0  
2       NaN  imdbDisplay          NaN                0.0  
3       NaN          NaN  short title                0.0  
4       NaN  imdbDisplay          NaN                0.0  
5       NaN  imdbDisplay          NaN                0.0  
6       NaN  imdbDisplay          NaN                0.0  
7       NaN  imdbDisplay          NaN                0.0  
8        he  imdbDisplay          NaN                0.0  
9       NaN  imdbDisplay          NaN                0.0  
10      NaN  imdbDisplay          NaN                0.0  
11      NaN  imdbDisplay          NaN                0.0  
12      NaN          NaN  3-D version                0.0  
13      NaN          NaN  3-D version                0.0  
14      NaN          NaN  3-D version                0.0  
15      NaN  imdbDisplay          NaN                0.0  
16      NaN  imdbDisplay          NaN                0.0  
17      NaN          NaN          NaN                0.0  
18      NaN          NaN          NaN                0.0  
19       fr  imdbDisplay          NaN                0.0

In [27]:
titleakas.tail(30)
#we can see titles of movies being printed here in multiple languages

title_id  ordering                                title region  \
331673  tt9562694         5                        Alien Warfare     US   
331674  tt9593792         1                           Ghost Wife     TH   
331675  tt9593792         2                           Ghost Wife    NaN   
331676  tt9593792         3                          Nguoi Vo Ma     VN   
331677  tt9644084         1                             Der Atem     DE   
331678  tt9644084         2                             Der Atem    NaN   
331679  tt9644084         3                           The Breath    XWW   
331680  tt9654246         1            The Wild Man of the North    XWW   
331681  tt9654246         2                      Vildmarkens søn     NO   
331682  tt9654246         3                      Vildmarkens søn    NaN   
331683  tt9657946         1                               Homing    XWW   
331684  tt9657946         2                            Querência     BR   
331685  tt9657946         3                            Querência    NaN   
331686  tt9705860         1  Dusan Vukotic Croatian Oscar Winner     US   
331687  tt9705860         2      Dusan Vukotic hrvatski okarovac    NaN   
331688  tt9705860         3      Dusan Vukotic hrvatski okarovac     HR   
331689  tt9723084         1           Anderswo. Allein in Afrika     DE   
331690  tt9723084         2           Anderswo. Allein in Afrika    NaN   
331691  tt9726638         1                   Qi Tian Da Sheng 2     CN   
331692  tt9726638         2             Monkey King: The Volcano    NaN   
331693  tt9726638         3        Qi Tian Da Sheng Huo Yan Shan     CN   
331694  tt9755806         1                            Big Shark     US   
331695  tt9755806         2                        Большая Акула     RU   
331696  tt9755806         3                            Big Shark    NaN   
331697  tt9827784         1                   Sayonara kuchibiru     JP   
331698  tt9827784         2                   Sayonara kuchibiru    NaN   
331699  tt9827784         3                        Farewell Song    XWW   
331700  tt9880178         1                          La atención    NaN   
331701  tt9880178         2                          La atención     ES   
331702  tt9880178         3                        The Attention    XWW   

       language        types attributes  is_original_title  
331673      NaN  imdbDisplay        NaN                0.0  
331674      NaN          NaN        NaN                0.0  
331675      NaN     original        NaN                1.0  
331676      NaN  imdbDisplay        NaN                0.0  
331677      NaN          NaN        NaN                0.0  
331678      NaN     original        NaN                1.0  
331679       en  alternative        NaN                0.0  
331680       en  imdbDisplay        NaN                0.0  
331681      NaN          NaN        NaN                0.0  
331682      NaN     original        NaN                1.0  
331683       en  imdbDisplay        NaN                0.0  
331684      NaN          NaN        NaN                0.0  
331685      NaN     original        NaN                1.0  
331686      NaN  imdbDisplay        NaN                0.0  
331687      NaN     original        NaN                1.0  
331688      NaN          NaN        NaN                0.0  
331689      NaN  imdbDisplay        NaN                0.0  
331690      NaN     original        NaN                1.0  
331691      yue  imdbDisplay        NaN                0.0  
331692      NaN     original        NaN                1.0  
331693      yue  imdbDisplay        NaN                0.0  
331694      NaN          NaN        NaN                0.0  
331695      NaN          NaN        NaN                0.0  
331696      NaN     original        NaN                1.0  
331697      NaN          NaN        NaN                0.0  
331698      NaN     original        NaN                1.0  
331699       en  imdbDisplay        

This is all quite interesting information but not what I was really hoping to find. I'm going to go back to my initial plan of combining my two Rotten Tomatoes data sets and see where it takes me.

## Rotten Tomatoes Data Merge

In [11]:
#Rotten Tomatoes Movies List- DF
rotten.head()

id                                           synopsis rating  \
0   1  This gritty, fast-paced, and innovative police...      R   
1   3  New York City, not-too-distant-future: Eric Pa...      R   
2   5  Illeana Douglas delivers a superb performance ...      R   
3   6  Michael Douglas runs afoul of a treacherous su...      R   
4   7                                                NaN     NR   

                                 genre          director  \
0  Action and Adventure|Classics|Drama  William Friedkin   
1    Drama|Science Fiction and Fantasy  David Cronenberg   
2    Drama|Musical and Performing Arts    Allison Anders   
3           Drama|Mystery and Suspense    Barry Levinson   
4                        Drama|Romance    Rodney Bennett   

                            writer  theater_date      dvd_date currency  \
0                   Ernest Tidyman   Oct 9, 1971  Sep 25, 2001      NaN   
1     David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
2                   Allison Anders  Sep 13, 1996  Apr 18, 2000      NaN   
3  Paul Attanasio|Michael Crichton   Dec 9, 1994  Aug 27, 1997      NaN   
4                     Giles Cooper           NaN           NaN      NaN   

  box_office      runtime             studio  
0        NaN  104 minutes                NaN  
1    600,000  108 minutes  Entertainment One  
2        NaN  116 minutes                NaN  
3        NaN  128 minutes                NaN  
4        NaN  200 minutes                NaN

In [7]:
rotten["synopsis"][0]
rotten["synopsis"][1]
#im beginning to think that the only way to find out the movie title affiliated with the review in the data is if it is mentioned in the synopsis, or if somehow we can get it by matching ID with another column..
#movie title probably is not important though, as we want to measure positive/negative reviews/sentiment/etc
#and come up with a meaningful conclusion

"New York City, not-too-distant-future: Eric Packer, a 28 year-old finance golden boy dreaming of living in a civilization ahead of this one, watches a dark shadow cast over the firmament of the Wall Street galaxy, of which he is the uncontested king. As he is chauffeured across midtown Manhattan to get a haircut at his father's old barber, his anxious eyes are glued to the yuan's exchange rate: it is mounting against all expectations, destroying Eric's bet against it. Eric Packer is losing his empire with every tick of the clock. Meanwhile, an eruption of wild activity unfolds in the city's streets. Petrified as the threats of the real world infringe upon his cloud of virtual convictions, his paranoia intensifies during the course of his 24-hour cross-town odyssey. Packer starts to piece together clues that lead him to a most terrifying secret: his imminent assassination. -- (C) Official Site"

In [6]:
rtreviews.head()

id                                             review rating   fresh  \
0   3  A distinctly gallows take on contemporary fina...    3/5   fresh   
1   3  It's an allegory in search of a meaning that n...    NaN  rotten   
2   3  ... life lived in a bubble in financial dealin...    NaN   fresh   
3   3  Continuing along a line introduced in last yea...    NaN   fresh   
4   3             ... a perverse twist on neorealism...     NaN   fresh   

           critic  top_critic         publisher               date  
0      PJ Nabarro           0   Patrick Nabarro  November 10, 2018  
1  Annalee Newitz           0           io9.com       May 23, 2018  
2    Sean Axmaker           0  Stream on Demand    January 4, 2018  
3   Daniel Kasman           0              MUBI  November 16, 2017  
4             NaN           0      Cinema Scope   October 12, 2017

In [67]:
rtreviews['rating'].value_counts()
#how many different "rating" values are there?
#looks like the rating data requires a LOT of cleaning, lets filter by freshness first

3/5       4327
4/5       3672
3/4       3577
2/5       3160
2/4       2712
          ... 
4.9          1
3.1          1
7.4          1
F+           1
4.3/10       1
Name: rating, Length: 186, dtype: int64

In [70]:
rtreviews['fresh'].value_counts()
#a Red tomato is fresh, which means 60% of the reviews are positive

fresh     33035
rotten    21397
Name: fresh, dtype: int64

In [51]:
rtreviews['id'].value_counts()

782     338
1067    275
1525    262
1777    260
1083    260
       ... 
28        1
102       1
348       1
476       1
1727      1
Name: id, Length: 1135, dtype: int64

In [52]:
rtreviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54432 entries, 0 to 54431
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          54432 non-null  int64 
 1   review      48869 non-null  object
 2   rating      40915 non-null  object
 3   fresh       54432 non-null  object
 4   critic      51710 non-null  object
 5   top_critic  54432 non-null  int64 
 6   publisher   54123 non-null  object
 7   date        54432 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.3+ MB


In [53]:
rotten.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            1560 non-null   int64 
 1   synopsis      1498 non-null   object
 2   rating        1557 non-null   object
 3   genre         1552 non-null   object
 4   director      1361 non-null   object
 5   writer        1111 non-null   object
 6   theater_date  1201 non-null   object
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    object
 10  runtime       1530 non-null   object
 11  studio        494 non-null    object
dtypes: int64(1), object(11)
memory usage: 146.4+ KB


In [59]:
#Cannot seem to find a way to determine the movie title. But perhaps we can get information on genre, rating, dates, review type, etc.

Alright, I have a better sense of the types of values found in both data sets. Now I am ready to begin merging.

In [8]:
#heroes_and_powers_df = heroes_df.merge(powers_df_transposed, on="name", how="inner")

rot = rotten.merge(rtreviews, on='id', how='inner')

rot.columns

Index(['id', 'synopsis', 'rating_x', 'genre', 'director', 'writer',
       'theater_date', 'dvd_date', 'currency', 'box_office', 'runtime',
       'studio', 'review', 'rating_y', 'fresh', 'critic', 'top_critic',
       'publisher', 'date'],
      dtype='object')

In [9]:
#I want to rename the column "rating_x" to say Rated, to distinguish it from a RT rating, since the values of rating_x are PG, R, etc.

rot = rot.rename(columns={"rating_x": "Rated"})

In [24]:
rot

id                                           synopsis Rated  \
0         3  New York City, not-too-distant-future: Eric Pa...     R   
1         3  New York City, not-too-distant-future: Eric Pa...     R   
2         3  New York City, not-too-distant-future: Eric Pa...     R   
3         3  New York City, not-too-distant-future: Eric Pa...     R   
4         3  New York City, not-too-distant-future: Eric Pa...     R   
...     ...                                                ...   ...   
54427  2000  Suspended from the force, Paris cop Hubert is ...     R   
54428  2000  Suspended from the force, Paris cop Hubert is ...     R   
54429  2000  Suspended from the force, Paris cop Hubert is ...     R   
54430  2000  Suspended from the force, Paris cop Hubert is ...     R   
54431  2000  Suspended from the force, Paris cop Hubert is ...     R   

                                                   genre          director  \
0                      Drama|Science Fiction and Fantasy  David Cronenberg   
1                      Drama|Science Fiction and Fantasy  David Cronenberg   
2                      Drama|Science Fiction and Fantasy  David Cronenberg   
3                      Drama|Science Fiction and Fantasy  David Cronenberg   
4                      Drama|Science Fiction and Fantasy  David Cronenberg   
...                                                  ...               ...   
54427  Action and Adventure|Art House and Internation...               NaN   
54428  Action and Adventure|Art House and Internation...               NaN   
54429  Action and Adventure|Art House and Internation...               NaN   
54430  Action and Adventure|Art House and Internation...               NaN   
54431  Action and Adventure|Art House and Internation...               NaN   

                             writer  theater_date      dvd_date currency  \
0      David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
1      David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
2      David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
3      David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
4      David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
...                             ...           ...           ...      ...   
54427                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54428                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54429                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54430                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54431                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   

      box_office      runtime             studio  \
0        600,000  108 minutes  Entertainment One   
1        600,000  108 minutes  Entertainment One   
2        600,000  108 minutes  Entertainment One   
3        600,000  108 minutes  Entertainment One   
4        600,000  108 minutes  Entertainment One   
...          ...          ...                ...   
54427        NaN   94 minutes  Columbia Pictures   
54428        NaN   94 minutes  Columbia Pictures   
54429        NaN   94 minutes  Columbia Pictures   
54430        NaN   94 minutes  Columbia Pictures   
54431        NaN   94 minutes  Columbia Pictures   

                                                  review rating_y   fresh  \
0      A distinctly gallows take on contemporary fina...      3/5   fresh   
1      It's an allegory in search of a meaning that n...      NaN  rotten   
2      ... life lived in a bubble in financial dealin...      NaN   fresh   
3      Continuing along a line introduced in last yea...      NaN   fresh   
4                 ... a perverse twist on neorealism...       NaN   fresh   
...                                                  ...      ...     ...   
54427  The real charm of this trifle is the deadpan c...      NaN   fresh   
54428                                                

In [196]:
droppeddirs = rot.loc[rot["genre"] == "Documentary|Special Interest"]
droppeddirs["director"].value_counts()

Adam Ravetch|Sarah Robertson                   93
Matt Tynauer|Matt Tyrnauer                     70
Leslie Cockburn                                32
Peter Byck                                     15
Errol Morris                                   11
Tim Nackashi|David Sampliner|Eric DelaBarre     6
Brent Leung                                     3
Emile de Antonio|Dan Talbot                     1
Name: director, dtype: int64

In [10]:
rot["Rated"].value_counts()

R        24371
PG-13    18008
PG        8246
NR        2650
G         1071
Name: Rated, dtype: int64

In [11]:
rot["studio"].value_counts()

Universal Pictures         4422
Paramount Pictures         3141
20th Century Fox           2415
Sony Pictures              2135
Sony Pictures Classics     2094
                           ... 
Knowledge Matters             3
Corridor                      1
Fox                           1
MVD Entertainment Group       1
Gravitas                      1
Name: studio, Length: 162, dtype: int64

In [12]:
rot = rot.rename(columns={"rating_y": "Rating"})

In [13]:
rot["Rating"].value_counts()[:20]

3/5      4327
4/5      3672
3/4      3577
2/5      3160
2/4      2712
2.5/4    2381
3.5/4    1777
3.5/5    1289
5/5      1237
B        1163
1/5      1113
1.5/4    1095
4/4       995
2.5/5     992
B+        832
1/4       822
B-        821
C         779
C+        665
4.5/5     567
Name: Rating, dtype: int64

In [39]:
rot["Rating"].value_counts()[20:40]

7/10     522
A-       514
8/10     505
C-       493
6/10     468
1.5/5    405
A        397
5/10     351
D        324
9/10     304
4/10     252
D+       204
0/5      162
8        143
3/10     140
1        138
0/4      132
7        125
F        109
0.5/4    100
Name: Rating, dtype: int64

The ratings for each film aren't very consistent, but looking at these value counts, I think I will try splitting out any of the reviews I can find that are x/5 to seek any consistent findings. 

In [14]:
relevant_ratings_5 = ["3/5", "4/5", "2/5", "3.5/5", "5/5", "1/5", "2.5/5", "4.5/5", "1.5/5", "0/5"]

In [15]:
ratings_out_of_5 = (rot.loc[rot['Rating'].isin(relevant_ratings_5)])

In [42]:
ratings_out_of_5

id                                           synopsis Rated  \
0         3  New York City, not-too-distant-future: Eric Pa...     R   
7         3  New York City, not-too-distant-future: Eric Pa...     R   
15        3  New York City, not-too-distant-future: Eric Pa...     R   
16        3  New York City, not-too-distant-future: Eric Pa...     R   
23        3  New York City, not-too-distant-future: Eric Pa...     R   
...     ...                                                ...   ...   
54424  2000  Suspended from the force, Paris cop Hubert is ...     R   
54428  2000  Suspended from the force, Paris cop Hubert is ...     R   
54429  2000  Suspended from the force, Paris cop Hubert is ...     R   
54430  2000  Suspended from the force, Paris cop Hubert is ...     R   
54431  2000  Suspended from the force, Paris cop Hubert is ...     R   

                                                   genre          director  \
0                      Drama|Science Fiction and Fantasy  David Cronenberg   
7                      Drama|Science Fiction and Fantasy  David Cronenberg   
15                     Drama|Science Fiction and Fantasy  David Cronenberg   
16                     Drama|Science Fiction and Fantasy  David Cronenberg   
23                     Drama|Science Fiction and Fantasy  David Cronenberg   
...                                                  ...               ...   
54424  Action and Adventure|Art House and Internation...               NaN   
54428  Action and Adventure|Art House and Internation...               NaN   
54429  Action and Adventure|Art House and Internation...               NaN   
54430  Action and Adventure|Art House and Internation...               NaN   
54431  Action and Adventure|Art House and Internation...               NaN   

                             writer  theater_date      dvd_date currency  \
0      David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
7      David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
15     David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
16     David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
23     David Cronenberg|Don DeLillo  Aug 17, 2012   Jan 1, 2013        $   
...                             ...           ...           ...      ...   
54424                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54428                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54429                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54430                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   
54431                    Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN   

      box_office      runtime             studio  \
0        600,000  108 minutes  Entertainment One   
7        600,000  108 minutes  Entertainment One   
15       600,000  108 minutes  Entertainment One   
16       600,000  108 minutes  Entertainment One   
23       600,000  108 minutes  Entertainment One   
...          ...          ...                ...   
54424        NaN   94 minutes  Columbia Pictures   
54428        NaN   94 minutes  Columbia Pictures   
54429        NaN   94 minutes  Columbia Pictures   
54430        NaN   94 minutes  Columbia Pictures   
54431        NaN   94 minutes  Columbia Pictures   

                                                  review Rating   fresh  \
0      A distinctly gallows take on contemporary fina...    3/5   fresh   
7      Cronenberg is not a director to be daunted by ...    2/5  rotten   
15     For better or worse - often both - Cosmopolis ...    3/5   fresh   
16     For one of the smartest films I've seen in a w...    4/5   fresh   
23     Those who said Don DeLillo's book was unfilmab...    2/5  rotten   
...                                                  ...    ...     ...   
54424  Dawdles and drags when it should pop; it doesn...  1.5/5  rotten   
54428                                                NaN    1/5  rott

In [43]:
ratings_out_of_5.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16924 entries, 0 to 54431
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            16924 non-null  int64 
 1   synopsis      16889 non-null  object
 2   Rated         16908 non-null  object
 3   genre         16908 non-null  object
 4   director      15267 non-null  object
 5   writer        14002 non-null  object
 6   theater_date  16451 non-null  object
 7   dvd_date      16451 non-null  object
 8   currency      9290 non-null   object
 9   box_office    9290 non-null   object
 10  runtime       16635 non-null  object
 11  studio        11014 non-null  object
 12  review        13302 non-null  object
 13  Rating        16924 non-null  object
 14  fresh         16924 non-null  object
 15  critic        15840 non-null  object
 16  top_critic    16924 non-null  int64 
 17  publisher     16799 non-null  object
 18  date          16924 non-null  object
dtypes: i

In [44]:
ratings_out_of_5["Rating"].value_counts()

3/5      4327
4/5      3672
2/5      3160
3.5/5    1289
5/5      1237
1/5      1113
2.5/5     992
4.5/5     567
1.5/5     405
0/5       162
Name: Rating, dtype: int64

Now I have a more measurable set of ratings, since I extracted all of the ratings that were scaled 0-5.

In [16]:
ratings_out_of_5["studio"].value_counts()[:20]

Universal Pictures          1154
Paramount Pictures           802
20th Century Fox             678
Sony Pictures                639
Sony Pictures Classics       604
Warner Bros. Pictures        499
The Weinstein Company        303
Columbia Pictures            292
Fox Searchlight Pictures     282
Walt Disney Pictures         269
MGM                          258
Warner Bros.                 218
Focus Features               215
Miramax Films                212
Roadside Attractions         186
New Line Cinema              174
Paramount Vantage            160
Summit Entertainment         158
Lionsgate Films              148
Newmarket Film Group         124
Name: studio, dtype: int64

My thoughts right now are... I want to explore the following:
1) Is there a correlation between the rating and the studio? Are certain studios gaining better reviews from the critics than the others?
2) Do certain genres receive poorer or better ratings? Which should we avoid, or which may be a winner with the crowds?
3) What dates are we working with in this set? I will probably use theater_date to start.

In [17]:
top20studios = ratings_out_of_5["studio"].value_counts()[:20].index

In [49]:
top20studios

Index(['Universal Pictures', 'Paramount Pictures', '20th Century Fox',
       'Sony Pictures', 'Sony Pictures Classics', 'Warner Bros. Pictures',
       'The Weinstein Company', 'Columbia Pictures',
       'Fox Searchlight Pictures', 'Walt Disney Pictures', 'MGM',
       'Warner Bros.', 'Focus Features', 'Miramax Films',
       'Roadside Attractions', 'New Line Cinema', 'Paramount Vantage',
       'Summit Entertainment', 'Lionsgate Films', 'Newmarket Film Group'],
      dtype='object')

In [18]:
#ratings_out_of_5 = (rot.loc[rot['Rating'].isin(relevant_ratings_5)])
top20studios_df = ratings_out_of_5.loc[ratings_out_of_5["studio"].isin(top20studios)]

In [51]:
top20studios_df

id                                           synopsis Rated  \
243       8  The year is 1942. As the Allies unite overseas...    PG   
248       8  The year is 1942. As the Allies unite overseas...    PG   
254       8  The year is 1942. As the Allies unite overseas...    PG   
263       8  The year is 1942. As the Allies unite overseas...    PG   
271       8  The year is 1942. As the Allies unite overseas...    PG   
...     ...                                                ...   ...   
54424  2000  Suspended from the force, Paris cop Hubert is ...     R   
54428  2000  Suspended from the force, Paris cop Hubert is ...     R   
54429  2000  Suspended from the force, Paris cop Hubert is ...     R   
54430  2000  Suspended from the force, Paris cop Hubert is ...     R   
54431  2000  Suspended from the force, Paris cop Hubert is ...     R   

                                                   genre     director  \
243                                Drama|Kids and Family  Jay Russell   
248                                Drama|Kids and Family  Jay Russell   
254                                Drama|Kids and Family  Jay Russell   
263                                Drama|Kids and Family  Jay Russell   
271                                Drama|Kids and Family  Jay Russell   
...                                                  ...          ...   
54424  Action and Adventure|Art House and Internation...          NaN   
54428  Action and Adventure|Art House and Internation...          NaN   
54429  Action and Adventure|Art House and Internation...          NaN   
54430  Action and Adventure|Art House and Internation...          NaN   
54431  Action and Adventure|Art House and Internation...          NaN   

                writer  theater_date      dvd_date currency box_office  \
243    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
248    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
254    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
263    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
271    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
...                ...           ...           ...      ...        ...   
54424       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54428       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54429       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54430       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54431       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   

          runtime                 studio  \
243    95 minutes  Warner Bros. Pictures   
248    95 minutes  Warner Bros. Pictures   
254    95 minutes  Warner Bros. Pictures   
263    95 minutes  Warner Bros. Pictures   
271    95 minutes  Warner Bros. Pictures   
...           ...                    ...   
54424  94 minutes      Columbia Pictures   
54428  94 minutes      Columbia Pictures   
54429  94 minutes      Columbia Pictures   
54430  94 minutes      Columbia Pictures   
54431  94 minutes      Columbia Pictures   

                                                  review Rating   fresh  \
243    Great boy-and-dog tale, but be prepared for te...    4/5   fresh   
248    They may find themselves mystified and a littl...  2.5/5  rotten   
254                           Lyrical and very touching.    4/5   fresh   
263    The movie doesn't so much tug at your heart as...  3.5/5   fresh   
271        Are guaranteed to cause alarm and even tears.    4/5   fresh   
...                                                  ...    ...     ...   
54424  Dawdles and drags when it should pop; it doesn...  1.5/5  rotten   
54428                                                NaN    1/5  rotten   
54429                                                NaN    2/5  rotten   
54430                                                NaN  2.5/5  rotten   
54431                   

In [53]:
len(top20studios_df['id'].unique())

220

My new dataframe, top20studios_df, narrows our movie review data to approx. 7,300 reviews, which seems to match up to 220 different movies. We can always increase these numbers if need be, but I want to see if there is any connection with the most reviewed studios, as this could mean these movies are the most commonly watched, thus could give us some important information.

In [54]:
top20studios_df["theater_date"].value_counts()

Jan 9, 2015     153
Nov 21, 2007    128
Aug 3, 2018     117
Aug 13, 2010    114
Dec 1, 2017     104
               ... 
Sep 1, 2000       8
Nov 10, 1999      8
Jun 11, 2004      5
Oct 13, 1981      3
Dec 25, 1974      2
Name: theater_date, Length: 203, dtype: int64

At first glance, we can see that there are movies from all different eras included in our set.

In [55]:
top20studios_df["theater_date"].value_counts()[:20]

Jan 9, 2015     153
Nov 21, 2007    128
Aug 3, 2018     117
Aug 13, 2010    114
Dec 1, 2017     104
Mar 9, 2012     102
May 20, 2016    101
Nov 9, 2012      86
Dec 14, 2012     79
Nov 25, 2011     79
Nov 20, 2015     77
Nov 28, 2014     77
Mar 16, 2018     72
Dec 20, 2013     72
Aug 12, 2016     69
Oct 16, 2015     69
Oct 22, 2010     67
Nov 23, 2012     66
Jan 14, 2011     64
Aug 23, 2013     64
Name: theater_date, dtype: int64

In [59]:
jan92015 = top20studios_df.loc[top20studios_df["theater_date"] == "Jan 9, 2015"]

In [61]:
jan92015["id"].value_counts()
#was just testing if this release date served any relevance being the most common, but it is only affiliated with 2 different movies

1960    94
689     59
Name: id, dtype: int64

I think I want to replace all the ratings in my data set so that I could plot them. So 3.5/5 will turn into just 3.5.

In [63]:
ratings_out_of_5["Rating"].value_counts()

3/5      4327
4/5      3672
2/5      3160
3.5/5    1289
5/5      1237
1/5      1113
2.5/5     992
4.5/5     567
1.5/5     405
0/5       162
Name: Rating, dtype: int64

In [19]:
top20_ratings_copy = top20studios_df.copy() #just incase i screw up the column value replacements

In [91]:
top20_ratings_copy

id                                           synopsis Rated  \
243       8  The year is 1942. As the Allies unite overseas...    PG   
248       8  The year is 1942. As the Allies unite overseas...    PG   
254       8  The year is 1942. As the Allies unite overseas...    PG   
263       8  The year is 1942. As the Allies unite overseas...    PG   
271       8  The year is 1942. As the Allies unite overseas...    PG   
...     ...                                                ...   ...   
54424  2000  Suspended from the force, Paris cop Hubert is ...     R   
54428  2000  Suspended from the force, Paris cop Hubert is ...     R   
54429  2000  Suspended from the force, Paris cop Hubert is ...     R   
54430  2000  Suspended from the force, Paris cop Hubert is ...     R   
54431  2000  Suspended from the force, Paris cop Hubert is ...     R   

                                                   genre     director  \
243                                Drama|Kids and Family  Jay Russell   
248                                Drama|Kids and Family  Jay Russell   
254                                Drama|Kids and Family  Jay Russell   
263                                Drama|Kids and Family  Jay Russell   
271                                Drama|Kids and Family  Jay Russell   
...                                                  ...          ...   
54424  Action and Adventure|Art House and Internation...          NaN   
54428  Action and Adventure|Art House and Internation...          NaN   
54429  Action and Adventure|Art House and Internation...          NaN   
54430  Action and Adventure|Art House and Internation...          NaN   
54431  Action and Adventure|Art House and Internation...          NaN   

                writer  theater_date      dvd_date currency box_office  \
243    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
248    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
254    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
263    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
271    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
...                ...           ...           ...      ...        ...   
54424       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54428       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54429       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54430       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54431       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   

          runtime                 studio  \
243    95 minutes  Warner Bros. Pictures   
248    95 minutes  Warner Bros. Pictures   
254    95 minutes  Warner Bros. Pictures   
263    95 minutes  Warner Bros. Pictures   
271    95 minutes  Warner Bros. Pictures   
...           ...                    ...   
54424  94 minutes      Columbia Pictures   
54428  94 minutes      Columbia Pictures   
54429  94 minutes      Columbia Pictures   
54430  94 minutes      Columbia Pictures   
54431  94 minutes      Columbia Pictures   

                                                  review Rating   fresh  \
243    Great boy-and-dog tale, but be prepared for te...    4/5   fresh   
248    They may find themselves mystified and a littl...  2.5/5  rotten   
254                           Lyrical and very touching.    4/5   fresh   
263    The movie doesn't so much tug at your heart as...  3.5/5   fresh   
271        Are guaranteed to cause alarm and even tears.    4/5   fresh   
...                                                  ...    ...     ...   
54424  Dawdles and drags when it should pop; it doesn...  1.5/5  rotten   
54428                                                NaN    1/5  rotten   
54429                                                NaN    2/5  rotten   
54430                                                NaN  2.5/5  rotten   
54431                   

In [20]:
#top20_ratings_copy = top20_ratings_copy["Rating"].replace({"3/5": "3", "4/5": "4", "2/5": "2", "3.5/5": "3.5", 
#                                                           "5/5": "5", "1/5": "1", "2.5/5": "2.5", "4.5/5": "4.5", 
#                                                          "1.5/5": "1.5", "0/5": "0"}, inplace=True)

ratings_replace_dict = {"3/5": "3", "4/5": "4", "2/5": "2", "3.5/5": "3.5", 
                        "5/5": "5", "1/5": "1", "2.5/5": "2.5", "4.5/5": "4.5", 
                        "1.5/5": "1.5", "0/5": "0"}

top20_ratings_replaced = top20studios_df["Rating"].replace(ratings_replace_dict, inplace=True)



C:\Users\saman\anaconda3\envs\learn-env\lib\site-packages\pandas\core\series.py:4563: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


In [21]:
top20studios_df
#looks like it worked...!!

id                                           synopsis Rated  \
243       8  The year is 1942. As the Allies unite overseas...    PG   
248       8  The year is 1942. As the Allies unite overseas...    PG   
254       8  The year is 1942. As the Allies unite overseas...    PG   
263       8  The year is 1942. As the Allies unite overseas...    PG   
271       8  The year is 1942. As the Allies unite overseas...    PG   
...     ...                                                ...   ...   
54424  2000  Suspended from the force, Paris cop Hubert is ...     R   
54428  2000  Suspended from the force, Paris cop Hubert is ...     R   
54429  2000  Suspended from the force, Paris cop Hubert is ...     R   
54430  2000  Suspended from the force, Paris cop Hubert is ...     R   
54431  2000  Suspended from the force, Paris cop Hubert is ...     R   

                                                   genre     director  \
243                                Drama|Kids and Family  Jay Russell   
248                                Drama|Kids and Family  Jay Russell   
254                                Drama|Kids and Family  Jay Russell   
263                                Drama|Kids and Family  Jay Russell   
271                                Drama|Kids and Family  Jay Russell   
...                                                  ...          ...   
54424  Action and Adventure|Art House and Internation...          NaN   
54428  Action and Adventure|Art House and Internation...          NaN   
54429  Action and Adventure|Art House and Internation...          NaN   
54430  Action and Adventure|Art House and Internation...          NaN   
54431  Action and Adventure|Art House and Internation...          NaN   

                writer  theater_date      dvd_date currency box_office  \
243    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
248    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
254    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
263    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
271    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
...                ...           ...           ...      ...        ...   
54424       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54428       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54429       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54430       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54431       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   

          runtime                 studio  \
243    95 minutes  Warner Bros. Pictures   
248    95 minutes  Warner Bros. Pictures   
254    95 minutes  Warner Bros. Pictures   
263    95 minutes  Warner Bros. Pictures   
271    95 minutes  Warner Bros. Pictures   
...           ...                    ...   
54424  94 minutes      Columbia Pictures   
54428  94 minutes      Columbia Pictures   
54429  94 minutes      Columbia Pictures   
54430  94 minutes      Columbia Pictures   
54431  94 minutes      Columbia Pictures   

                                                  review Rating   fresh  \
243    Great boy-and-dog tale, but be prepared for te...      4   fresh   
248    They may find themselves mystified and a littl...    2.5  rotten   
254                           Lyrical and very touching.      4   fresh   
263    The movie doesn't so much tug at your heart as...    3.5   fresh   
271        Are guaranteed to cause alarm and even tears.      4   fresh   
...                                                  ...    ...     ...   
54424  Dawdles and drags when it should pop; it doesn...    1.5  rotten   
54428                                                NaN      1  rotten   
54429                                                NaN      2  rotten   
54430                                                NaN    2.5  rotten   
54431                   

In [77]:
# Somehow, when I created a copy of my top 20 production companies DF, it created a "NoneType" object that I cannot work with. 
#Will need to investigate tomorrow in the AM.

In [22]:
top20studios_df["Rating"].value_counts()

3      1735
4      1521
2      1333
3.5     698
2.5     555
5       500
1       447
4.5     324
1.5     224
0        38
Name: Rating, dtype: int64

In [23]:
top20studios_df["Rating"].describe()

count     7375
unique      10
top          3
freq      1735
Name: Rating, dtype: object

In [103]:
top20studios_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7375 entries, 243 to 54431
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            7375 non-null   int64 
 1   synopsis      7375 non-null   object
 2   Rated         7375 non-null   object
 3   genre         7375 non-null   object
 4   director      6529 non-null   object
 5   writer        6198 non-null   object
 6   theater_date  7358 non-null   object
 7   dvd_date      7358 non-null   object
 8   currency      5990 non-null   object
 9   box_office    5990 non-null   object
 10  runtime       7266 non-null   object
 11  studio        7375 non-null   object
 12  review        6823 non-null   object
 13  Rating        7375 non-null   object
 14  fresh         7375 non-null   object
 15  critic        6863 non-null   object
 16  top_critic    7375 non-null   int64 
 17  publisher     7310 non-null   object
 18  date          7375 non-null   object
dtypes: 

In [24]:
top20studios_df["Rating"] = top20studios_df["Rating"].astype(str).astype(float)

<ipython-input-24-61fbc4f60a42>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top20studios_df["Rating"] = top20studios_df["Rating"].astype(str).astype(float)


In [25]:
top20studios_df

id                                           synopsis Rated  \
243       8  The year is 1942. As the Allies unite overseas...    PG   
248       8  The year is 1942. As the Allies unite overseas...    PG   
254       8  The year is 1942. As the Allies unite overseas...    PG   
263       8  The year is 1942. As the Allies unite overseas...    PG   
271       8  The year is 1942. As the Allies unite overseas...    PG   
...     ...                                                ...   ...   
54424  2000  Suspended from the force, Paris cop Hubert is ...     R   
54428  2000  Suspended from the force, Paris cop Hubert is ...     R   
54429  2000  Suspended from the force, Paris cop Hubert is ...     R   
54430  2000  Suspended from the force, Paris cop Hubert is ...     R   
54431  2000  Suspended from the force, Paris cop Hubert is ...     R   

                                                   genre     director  \
243                                Drama|Kids and Family  Jay Russell   
248                                Drama|Kids and Family  Jay Russell   
254                                Drama|Kids and Family  Jay Russell   
263                                Drama|Kids and Family  Jay Russell   
271                                Drama|Kids and Family  Jay Russell   
...                                                  ...          ...   
54424  Action and Adventure|Art House and Internation...          NaN   
54428  Action and Adventure|Art House and Internation...          NaN   
54429  Action and Adventure|Art House and Internation...          NaN   
54430  Action and Adventure|Art House and Internation...          NaN   
54431  Action and Adventure|Art House and Internation...          NaN   

                writer  theater_date      dvd_date currency box_office  \
243    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
248    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
254    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
263    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
271    Gail Gilchriest   Mar 3, 2000  Jul 11, 2000      NaN        NaN   
...                ...           ...           ...      ...        ...   
54424       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54428       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54429       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54430       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   
54431       Luc Besson  Sep 27, 2001  Feb 11, 2003      NaN        NaN   

          runtime                 studio  \
243    95 minutes  Warner Bros. Pictures   
248    95 minutes  Warner Bros. Pictures   
254    95 minutes  Warner Bros. Pictures   
263    95 minutes  Warner Bros. Pictures   
271    95 minutes  Warner Bros. Pictures   
...           ...                    ...   
54424  94 minutes      Columbia Pictures   
54428  94 minutes      Columbia Pictures   
54429  94 minutes      Columbia Pictures   
54430  94 minutes      Columbia Pictures   
54431  94 minutes      Columbia Pictures   

                                                  review  Rating   fresh  \
243    Great boy-and-dog tale, but be prepared for te...     4.0   fresh   
248    They may find themselves mystified and a littl...     2.5  rotten   
254                           Lyrical and very touching.     4.0   fresh   
263    The movie doesn't so much tug at your heart as...     3.5   fresh   
271        Are guaranteed to cause alarm and even tears.     4.0   fresh   
...                                                  ...     ...     ...   
54424  Dawdles and drags when it should pop; it doesn...     1.5  rotten   
54428                                                NaN     1.0  rotten   
54429                                                NaN     2.0  rotten   
54430                                                NaN     2.5  rotten   
54431        

In [26]:
top20studios_df["Rating"].value_counts()

3.0    1735
4.0    1521
2.0    1333
3.5     698
2.5     555
5.0     500
1.0     447
4.5     324
1.5     224
0.0      38
Name: Rating, dtype: int64

In [27]:
top20studios_df["Rating"].describe()

count    7375.000000
mean        3.054441
std         1.074168
min         0.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Rating, dtype: float64

Hooray! We have converted these ratings to floats so that the ratings are now measurable numbers.

In [37]:
#Now I want to do a GROUP BY comparing the production companies to their average rating

In [36]:
averagerating = top20studios_df.groupby(["studio"])["Rating"].mean().sort_values(ascending=False)
averagerating

studio
The Weinstein Company       4.079208
Miramax Films               3.627358
Fox Searchlight Pictures    3.592199
Sony Pictures Classics      3.452815
Focus Features              3.427907
Newmarket Film Group        3.346774
Roadside Attractions        3.250000
Paramount Vantage           3.250000
MGM                         3.100775
Paramount Pictures          3.072319
Walt Disney Pictures        3.068773
Warner Bros. Pictures       3.062124
Sony Pictures               2.888889
Universal Pictures          2.885615
Warner Bros.                2.834862
New Line Cinema             2.787356
Columbia Pictures           2.655822
Summit Entertainment        2.623418
20th Century Fox            2.566372
Lionsgate Films             2.162162
Name: Rating, dtype: float64

Based on this exploratory data analysis, there seem to be certain production companies (such as Weinstein Company, Miramax, Fox Searchlight) that receive overall better reviews than others. Although, my data was reduced pretty heavily. I want to compare this to the ratings of the entire data set. 

Since the data set's reviews are all over the place (some out of 10, some A- or D+, some out of 4), I think I will first assess rotten vs. fresh. 

Based on information I found online, "fresh" is indicateive of a 60% or higher review. Perhaps later I can convert all the ratings to percentages and go from there. But for now, I want to see if we get the same data re: production companies if we utilize the entire data set, but sort by freshness.

In [39]:
#bringing back our original merged dataframe "rot"

rot.head()

id                                           synopsis Rated  \
0   3  New York City, not-too-distant-future: Eric Pa...     R   
1   3  New York City, not-too-distant-future: Eric Pa...     R   
2   3  New York City, not-too-distant-future: Eric Pa...     R   
3   3  New York City, not-too-distant-future: Eric Pa...     R   
4   3  New York City, not-too-distant-future: Eric Pa...     R   

                               genre          director  \
0  Drama|Science Fiction and Fantasy  David Cronenberg   
1  Drama|Science Fiction and Fantasy  David Cronenberg   
2  Drama|Science Fiction and Fantasy  David Cronenberg   
3  Drama|Science Fiction and Fantasy  David Cronenberg   
4  Drama|Science Fiction and Fantasy  David Cronenberg   

                         writer  theater_date     dvd_date currency  \
0  David Cronenberg|Don DeLillo  Aug 17, 2012  Jan 1, 2013        $   
1  David Cronenberg|Don DeLillo  Aug 17, 2012  Jan 1, 2013        $   
2  David Cronenberg|Don DeLillo  Aug 17, 2012  Jan 1, 2013        $   
3  David Cronenberg|Don DeLillo  Aug 17, 2012  Jan 1, 2013        $   
4  David Cronenberg|Don DeLillo  Aug 17, 2012  Jan 1, 2013        $   

  box_office      runtime             studio  \
0    600,000  108 minutes  Entertainment One   
1    600,000  108 minutes  Entertainment One   
2    600,000  108 minutes  Entertainment One   
3    600,000  108 minutes  Entertainment One   
4    600,000  108 minutes  Entertainment One   

                                              review Rating   fresh  \
0  A distinctly gallows take on contemporary fina...    3/5   fresh   
1  It's an allegory in search of a meaning that n...    NaN  rotten   
2  ... life lived in a bubble in financial dealin...    NaN   fresh   
3  Continuing along a line introduced in last yea...    NaN   fresh   
4             ... a perverse twist on neorealism...     NaN   fresh   

           critic  top_critic         publisher               date  
0      PJ Nabarro           0   Patrick Nabarro  November 10, 2018  
1  Annalee Newitz           0           io9.com       May 23, 2018  
2    Sean Axmaker           0  Stream on Demand    January 4, 2018  
3   Daniel Kasman           0              MUBI  November 16, 2017  
4             NaN           0      Cinema Scope   October 12, 2017

In [40]:
rot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54432 entries, 0 to 54431
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            54432 non-null  int64 
 1   synopsis      54300 non-null  object
 2   Rated         54346 non-null  object
 3   genre         54345 non-null  object
 4   director      48992 non-null  object
 5   writer        45206 non-null  object
 6   theater_date  53206 non-null  object
 7   dvd_date      53206 non-null  object
 8   currency      33310 non-null  object
 9   box_office    33310 non-null  object
 10  runtime       53594 non-null  object
 11  studio        40125 non-null  object
 12  review        48869 non-null  object
 13  Rating        40915 non-null  object
 14  fresh         54432 non-null  object
 15  critic        51710 non-null  object
 16  top_critic    54432 non-null  int64 
 17  publisher     54123 non-null  object
 18  date          54432 non-null  object
dtypes: i

We can see here that there are NO missing values from the "fresh" column in this dataset, which indicates to me that it is very important to Rotten Tomato's ratings system. And will be helpful to us in gaging the success of all the movies in the set.

In [41]:
rot["fresh"].value_counts()

fresh     33035
rotten    21397
Name: fresh, dtype: int64

We have confirmed that the freshness column will return either "fresh" or "rotten". 

In [77]:
#im going to reduce some columns here for viewing purposes
#selected_columns = ['A', 'C', 'D']
#new = select_columns(old, selected_columns)

freshness_df = rot[["id","Rated","genre","director","studio","review","Rating","fresh","critic"]].copy()
freshness_df

id Rated                                              genre  \
0         3     R                  Drama|Science Fiction and Fantasy   
1         3     R                  Drama|Science Fiction and Fantasy   
2         3     R                  Drama|Science Fiction and Fantasy   
3         3     R                  Drama|Science Fiction and Fantasy   
4         3     R                  Drama|Science Fiction and Fantasy   
...     ...   ...                                                ...   
54427  2000     R  Action and Adventure|Art House and Internation...   
54428  2000     R  Action and Adventure|Art House and Internation...   
54429  2000     R  Action and Adventure|Art House and Internation...   
54430  2000     R  Action and Adventure|Art House and Internation...   
54431  2000     R  Action and Adventure|Art House and Internation...   

               director             studio  \
0      David Cronenberg  Entertainment One   
1      David Cronenberg  Entertainment One   
2      David Cronenberg  Entertainment One   
3      David Cronenberg  Entertainment One   
4      David Cronenberg  Entertainment One   
...                 ...                ...   
54427               NaN  Columbia Pictures   
54428               NaN  Columbia Pictures   
54429               NaN  Columbia Pictures   
54430               NaN  Columbia Pictures   
54431               NaN  Columbia Pictures   

                                                  review Rating   fresh  \
0      A distinctly gallows take on contemporary fina...    3/5   fresh   
1      It's an allegory in search of a meaning that n...    NaN  rotten   
2      ... life lived in a bubble in financial dealin...    NaN   fresh   
3      Continuing along a line introduced in last yea...    NaN   fresh   
4                 ... a perverse twist on neorealism...     NaN   fresh   
...                                                  ...    ...     ...   
54427  The real charm of this trifle is the deadpan c...    NaN   fresh   
54428                                                NaN    1/5  rotten   
54429                                                NaN    2/5  rotten   
54430                                                NaN  2.5/5  rotten   
54431                                                NaN    3/5   fresh   

                  critic  
0             PJ Nabarro  
1         Annalee Newitz  
2           Sean Axmaker  
3          Daniel Kasman  
4                    NaN  
...                  ...  
54427      Laura Sinagra  
54428  Michael Szymanski  
54429       Emanuel Levy  
54430   Christopher Null  
54431    Nicolas Lacroix  

[54432 rows x 9 columns]

In [78]:
freshness_replace = {"fresh":1, "rotten":0}
sorting_freshness = freshness_df["fresh"].replace(freshness_replace, inplace=True)
#studio duplicates - studio_replace = {}

In [79]:
freshness_df
#confirming that my new DF has a rating of 1 or 0 for freshness

id Rated                                              genre  \
0         3     R                  Drama|Science Fiction and Fantasy   
1         3     R                  Drama|Science Fiction and Fantasy   
2         3     R                  Drama|Science Fiction and Fantasy   
3         3     R                  Drama|Science Fiction and Fantasy   
4         3     R                  Drama|Science Fiction and Fantasy   
...     ...   ...                                                ...   
54427  2000     R  Action and Adventure|Art House and Internation...   
54428  2000     R  Action and Adventure|Art House and Internation...   
54429  2000     R  Action and Adventure|Art House and Internation...   
54430  2000     R  Action and Adventure|Art House and Internation...   
54431  2000     R  Action and Adventure|Art House and Internation...   

               director             studio  \
0      David Cronenberg  Entertainment One   
1      David Cronenberg  Entertainment One   
2      David Cronenberg  Entertainment One   
3      David Cronenberg  Entertainment One   
4      David Cronenberg  Entertainment One   
...                 ...                ...   
54427               NaN  Columbia Pictures   
54428               NaN  Columbia Pictures   
54429               NaN  Columbia Pictures   
54430               NaN  Columbia Pictures   
54431               NaN  Columbia Pictures   

                                                  review Rating  fresh  \
0      A distinctly gallows take on contemporary fina...    3/5      1   
1      It's an allegory in search of a meaning that n...    NaN      0   
2      ... life lived in a bubble in financial dealin...    NaN      1   
3      Continuing along a line introduced in last yea...    NaN      1   
4                 ... a perverse twist on neorealism...     NaN      1   
...                                                  ...    ...    ...   
54427  The real charm of this trifle is the deadpan c...    NaN      1   
54428                                                NaN    1/5      0   
54429                                                NaN    2/5      0   
54430                                                NaN  2.5/5      0   
54431                                                NaN    3/5      1   

                  critic  
0             PJ Nabarro  
1         Annalee Newitz  
2           Sean Axmaker  
3          Daniel Kasman  
4                    NaN  
...                  ...  
54427      Laura Sinagra  
54428  Michael Szymanski  
54429       Emanuel Levy  
54430   Christopher Null  
54431    Nicolas Lacroix  

[54432 rows x 9 columns]

In [80]:
s = pd.Series(freshness_df["fresh"])
freshness_df["fresh"] = pd.to_numeric(s)

In [82]:
freshness_df["fresh"]

0        1
1        0
2        1
3        1
4        1
        ..
54427    1
54428    0
54429    0
54430    0
54431    1
Name: fresh, Length: 54432, dtype: int64

In [83]:
averagefreshness = freshness_df.groupby(["studio"])["fresh"].mean().sort_values(ascending=False)

In [85]:
averagefreshness[:20]

studio
Fox                                        1.000000
Iskander Films                             1.000000
Corridor                                   1.000000
Criterion Collection                       1.000000
MVD Entertainment Group                    1.000000
Variance Films                             1.000000
Buffalo Films                              0.961538
STX Entertainment                          0.947059
Laemmle/Zeller Films                       0.939394
The Film Arcade                            0.937500
The Weinstein Company                      0.930624
United Artists Pictures                    0.927835
Fingerprint Releasing / Bleecker Street    0.926724
Film 44                                    0.916667
Film District                              0.905109
Universal                                  0.904762
Walt Disney Animation Studios              0.897727
Janus Films                                0.896226
Aviron Pictures                            0.882353
A24  

In [86]:
top_20_freshest = averagefreshness[:20].index

We see some variation from our original findings here when including all of the reviews and grouping them by freshness. It appears Fox, Iskander Films, Corridor, Criterion, MVD and Variance have all their ratings at a 60% or higher. 

That being said, Fox probably has a lot more reviews than some of these other companies. I want to now sort them by amount of reviews.

In [87]:
top_20_freshest

Index(['Fox', 'Iskander Films', 'Corridor', 'Criterion Collection',
       'MVD Entertainment Group', 'Variance Films', 'Buffalo Films',
       'STX Entertainment', 'Laemmle/Zeller Films', 'The Film Arcade',
       'The Weinstein Company', 'United Artists Pictures',
       'Fingerprint Releasing / Bleecker Street', 'Film 44', 'Film District',
       'Universal', 'Walt Disney Animation Studios', 'Janus Films',
       'Aviron Pictures', 'A24'],
      dtype='object', name='studio')

In [91]:
#freshness_and_counts = freshness_df.groupby(["studio"])["fresh"].count().sort_values(ascending=False)

In the below function, I am grouping my dataframe by studio and want to count the amount of "fresh" (60% and up) ratings they receive. 

In [94]:
freshness_and_counts = freshness_df.groupby('studio')['fresh'].apply(lambda x: x[x == 1].count()).sort_values(ascending=False)



In [120]:
freshness_and_counts[:37]

studio
Universal Pictures                         2373
Paramount Pictures                         1760
Sony Pictures Classics                     1586
Warner Bros. Pictures                      1157
Sony Pictures                              1133
20th Century Fox                           1008
The Weinstein Company                       939
Fox Searchlight Pictures                    802
Focus Features                              611
Walt Disney Pictures                        569
Miramax Films                               550
MGM                                         501
Columbia Pictures                           450
Paramount Vantage                           429
New Line Cinema                             402
Warner Bros.                                399
Roadside Attractions                        357
Newmarket Film Group                        350
Lions Gate Films                            289
Fox Searchlight                             263
Buena Vista Pictures             

In [100]:
len(freshness_df["studio"].unique())

163

With the above, I confirmed that my equation worked properly since my "freshness_and_counts" function printed 163 different counts, and the length of unique production studios in my dataframe is also 163.

Okay, now we can see that certain companies have significantly more reviews than others. In fact, companies like Iskander Films, Corridor, Criterion Collection, and MVD Entertainment Group were amongst the highest ratings of freshness, but theoretically could have just one or two ratings that are being measured.

In [104]:
freshness_and_counts.tail(10)

studio
Film Foundry Releasing            2
Freestyle Releasing               1
Fox                               1
Corridor                          1
Film Sales Company                1
MVD Entertainment Group           1
Gravitas                          0
Knowledge Matters                 0
20th Century Fox Film Corporat    0
Full Circle Releasing             0
Name: fresh, dtype: int64

Wow, it is confirmed that our initial mean calculation really doesn't mean much without accounting for the amount of reviews! Fox, Corridor, and MVD all only have a single review attached to their studio name! That isn't very measurable.

In [114]:
freshness_and_counts.describe()

count     162.000000
mean      147.283951
std       317.219685
min         0.000000
25%        13.250000
50%        38.000000
75%       131.250000
max      2373.000000
Name: fresh, dtype: float64

Based on the describe function of every movie review in our full data set that has at least one positive/"fresh" review, we can see that there is a huge variation of amounts of reviews that certain studios have received over others. I'm thinking right now the goal is to emulate which companies are having success, popularity that is reflected in their positive reviews. 

It looks like, out of the companies with any positive reviews, the average amount of entries is 147. So I will next filter out the companies that contain less than this many entries, for we want to take popularity into account.

In [124]:
#used descending counts function from before to determine all the companies that had at least 147 positive/"fresh" reviews

positive_reviews_companies = freshness_and_counts[:37].index

In [125]:
positive_reviews_companies

Index(['Universal Pictures', 'Paramount Pictures', 'Sony Pictures Classics',
       'Warner Bros. Pictures', 'Sony Pictures', '20th Century Fox',
       'The Weinstein Company', 'Fox Searchlight Pictures', 'Focus Features',
       'Walt Disney Pictures', 'Miramax Films', 'MGM', 'Columbia Pictures',
       'Paramount Vantage', 'New Line Cinema', 'Warner Bros.',
       'Roadside Attractions', 'Newmarket Film Group', 'Lions Gate Films',
       'Fox Searchlight', 'Buena Vista Pictures', 'DreamWorks SKG',
       'Fingerprint Releasing / Bleecker Street', 'USA Films', 'Universal',
       'Summit Entertainment', 'A24', 'A24 Films', 'Dimension Films', 'WB',
       'Paramount', 'STX Entertainment', 'Lionsgate Films',
       'Walt Disney Animation Studios', 'Buena Vista Distribution Compa',
       'IFC Films', 'Lionsgate'],
      dtype='object', name='studio')

In [128]:
#I am creating a new DF that keeps all companies with 147 positive reviews or more

positive_reviews_ratings_df = freshness_df.loc[freshness_df["studio"].isin(positive_reviews_companies)]

#freshness_df.groupby(["studio"])["Rating"].mean().sort_values(ascending=False)


In [129]:
positive_reviews_ratings_df

id Rated                                              genre  \
243       8    PG                              Drama|Kids and Family   
244       8    PG                              Drama|Kids and Family   
245       8    PG                              Drama|Kids and Family   
246       8    PG                              Drama|Kids and Family   
247       8    PG                              Drama|Kids and Family   
...     ...   ...                                                ...   
54427  2000     R  Action and Adventure|Art House and Internation...   
54428  2000     R  Action and Adventure|Art House and Internation...   
54429  2000     R  Action and Adventure|Art House and Internation...   
54430  2000     R  Action and Adventure|Art House and Internation...   
54431  2000     R  Action and Adventure|Art House and Internation...   

          director                 studio  \
243    Jay Russell  Warner Bros. Pictures   
244    Jay Russell  Warner Bros. Pictures   
245    Jay Russell  Warner Bros. Pictures   
246    Jay Russell  Warner Bros. Pictures   
247    Jay Russell  Warner Bros. Pictures   
...            ...                    ...   
54427          NaN      Columbia Pictures   
54428          NaN      Columbia Pictures   
54429          NaN      Columbia Pictures   
54430          NaN      Columbia Pictures   
54431          NaN      Columbia Pictures   

                                                  review Rating  fresh  \
243    Great boy-and-dog tale, but be prepared for te...    4/5      1   
244    Not a mawkish dying-dog tearjerker, "My Dog Sk...  3.5/4      1   
245    Features two irresistible lead characters -- a...  2.5/4      1   
246              A heart-affecting boy-with-a-dog drama.    NaN      1   
247            An affectionate and tender family film...     C+      0   
...                                                  ...    ...    ...   
54427  The real charm of this trifle is the deadpan c...    NaN      1   
54428                                                NaN    1/5      0   
54429                                                NaN    2/5      0   
54430                                                NaN  2.5/5      0   
54431                                                NaN    3/5      1   

                  critic  
243           Nell Minow  
244          Nick Rogers  
245       Judith Egerton  
246                  NaN  
247      Dennis Schwartz  
...                  ...  
54427      Laura Sinagra  
54428  Michael Szymanski  
54429       Emanuel Levy  
54430   Christopher Null  
54431    Nicolas Lacroix  

[31282 rows x 9 columns]

In [140]:
#Now I am going to get the average(mean) review score of these. We have a much larger data set to work with now, with 31,000 reviews.

#Need to convert the ratings to percentages... lots of cleaning going to be involved!

positive_reviews_ratings_df['Rating'].value_counts()[:50]



3/4       2242
3/5       1984
4/5       1888
2/4       1704
2.5/4     1518
2/5       1455
3.5/4     1152
3.5/5      849
1.5/4      727
B          726
4/4        632
2.5/5      614
5/5        579
B+         540
B-         519
C          500
1/5        487
1/4        468
C+         394
4.5/5      383
A-         341
8/10       327
6/10       305
C-         301
7/10       283
A          259
1.5/5      244
5/10       219
D          208
9/10       189
4/10       149
D+         130
1           85
3/10        82
8           69
0/4         68
F           59
7           55
D-          51
0.5/4       48
2/10        42
0/5         41
7.5/10      40
A+          38
6           36
8.5/10      35
0.5/5       30
5           25
3           22
5.5/10      21
Name: Rating, dtype: int64

So, so many review types. What a mess. I am now realizing that Rotten Tomatoes curates reviews from the web and converts them to their freshness scale, but many different movie news sources have their own rating scale. I want everything to be uniform so I will do my best to convert all of these to percentages. It's tedious but I think it will be worth it.


In [142]:
positive_reviews_ratings_df.loc[positive_reviews_ratings_df['Rating'] == "7"]

id  Rated                                              genre  \
1188     34  PG-13          Action and Adventure|Mystery and Suspense   
1949     57      R                                             Comedy   
2212     65     PG                     Comedy|Kids and Family|Romance   
3465    118     PG                 Comedy|Science Fiction and Fantasy   
7863    300  PG-13                                              Drama   
8602    322      R                                             Horror   
9158    338  PG-13                         Drama|Mystery and Suspense   
9277    346  PG-13                                      Drama|Romance   
9901    377      R           Comedy|Drama|Musical and Performing Arts   
11290   433  PG-13          Action and Adventure|Mystery and Suspense   
12642   488     PG                   Animation|Comedy|Kids and Family   
14012   564     PG              Action and Adventure|Animation|Comedy   
14016   564     PG              Action and Adventure|Animation|Comedy   
14999   596      G                       Documentary|Special Interest   
15971   646  PG-13                  Comedy|Drama|Mystery and Suspense   
16186   661     PG                                     Comedy|Romance   
23825   969      R                                       Comedy|Drama   
23890   969      R                                       Comedy|Drama   
24820  1009  PG-13                               Comedy|Drama|Romance   
25631  1038  PG-13                               Comedy|Drama|Romance   
25704  1038  PG-13                               Comedy|Drama|Romance   
25732  1038  PG-13                               Comedy|Drama|Romance   
28473  1136  PG-13   Action and Adventure|Science Fiction and Fantasy   
30077  1197      R  Art House and International|Drama|Special Inte...   
30686  1210  PG-13                               Comedy|Drama|Romance   
31579  1243  PG-13                                              Drama   
33194  1307  PG-13                                              Drama   
33323  1315     PG  Action and Adventure|Comedy|Kids and Family|My...   
33563  1320      R                                              Drama   
34588  1339     PG                                     Comedy|Romance   
35472  1381      R                                     Comedy|Romance   
36637  1424  PG-13  Action and Adventure|Horror|Kids and Family|Sc...   
36676  1424  PG-13  Action and Adventure|Horror|Kids and Family|Sc...   
36910  1435  PG-13                                             Comedy   
37197  1446  PG-13                                             Comedy   
38573  1487  PG-13                                     Comedy|Romance   
40689  1541     PG        Action and Adventure|Comedy|Kids and Family   
40766  1541     PG        Action and Adventure|Comedy|Kids and Family   
41884  1585  PG-13                                     Comedy|Romance   
43130  1618  PG-13  Action and Adventure|Art House and Internation...   
43587  1638      R                Comedy|Mystery and Suspense|Romance   
43924  1646      R                                              Drama   
46411  1750      R                                       Comedy|Drama   
47094  1767      R           Comedy|Drama|Horror|Mystery and Suspense   
47290  1775      R                  Action and Adventure|Comedy|Drama   
47430  1777      R    Action and Adventure|Drama|Mystery and Suspense   
49227  1837     PG                                      Drama|Romance   
49512  1844      R                                       Comedy|Drama   
50988  1890      R                                   Animation|Comedy   
52084  1935  PG-13  Action and Adventure|Mystery and Suspense|Scie...   
52102  1935  PG-13  Action and Adventure|Mystery and Suspense|Scie...   
52712  1946      R                        Horror|Mystery and Suspense   
52789  1947  PG-13                  Art House and International|Drama   
53275  1962  PG-13                                       Comedy|Dra

I am unfortunately going to need to drop anything that does not have a clear scale. For example, in the above DF locator, I tested all values that had a rating of 7. You can see that some are fresh, and some aren't. Most would assume a 7/10, which would equal a 70% and fall into the "fresh" category...

In [154]:
A_rating = positive_reviews_ratings_df.loc[positive_reviews_ratings_df['Rating'] == "A"]
A_rating["fresh"].value_counts()
#of course, all A ratings should be fresh

1    259
Name: fresh, dtype: int64

It is safe to say that we can include A ratings in our data set.

There are a LOT of B's! Let's test those out.

In [155]:
B_rating = positive_reviews_ratings_df.loc[positive_reviews_ratings_df['Rating'] == "B"]
B_rating["fresh"].value_counts()

1    725
0      1
Name: fresh, dtype: int64

Okay, besides one outlier, all of the B's are fresh across the board. Perfect.

In [157]:
Bminus_rating = positive_reviews_ratings_df.loc[positive_reviews_ratings_df['Rating'] == "B-"]
Bminus_rating["fresh"].value_counts()
#most Bminus ratings are fresh

1    491
0     28
Name: fresh, dtype: int64

In [150]:
C_rating = positive_reviews_ratings_df.loc[positive_reviews_ratings_df['Rating'] == "C"]
C_rating["fresh"].value_counts()

0    490
1     10
Name: fresh, dtype: int64

Okay, so it is pretty safe to assume that a "C" rating is not fresh. So far it is looking like we can trust the letter grades to include in our data analysis, but I want to test some more.

In [152]:
Cplus_rating = positive_reviews_ratings_df.loc[positive_reviews_ratings_df['Rating'] == "C+"]
Cplus_rating["fresh"].value_counts()

0    336
1     58
Name: fresh, dtype: int64

Uh oh, a C+ rating actually has a bit more of a discrepancy than a C rating. The goal is for us to assess the positive reviews only, so let's move on to more rating scales.

It just dawned on me that I can drop the non-fresh values and probably will have a more clear indicator of which ratings correlate to the "fresh" indicator on the freshness scale.

I also have noticed a lot of duplicates in the studio names... I will clean those up as well with a dictionary. I think these two changes will make our data a lot cleaner.
1) Fix duplicate studios and 2) Drop non-fresh movie ratings to gage the successful movies only

In [160]:
positive_reviews_companies

Index(['Universal Pictures', 'Paramount Pictures', 'Sony Pictures Classics',
       'Warner Bros. Pictures', 'Sony Pictures', '20th Century Fox',
       'The Weinstein Company', 'Fox Searchlight Pictures', 'Focus Features',
       'Walt Disney Pictures', 'Miramax Films', 'MGM', 'Columbia Pictures',
       'Paramount Vantage', 'New Line Cinema', 'Warner Bros.',
       'Roadside Attractions', 'Newmarket Film Group', 'Lions Gate Films',
       'Fox Searchlight', 'Buena Vista Pictures', 'DreamWorks SKG',
       'Fingerprint Releasing / Bleecker Street', 'USA Films', 'Universal',
       'Summit Entertainment', 'A24', 'A24 Films', 'Dimension Films', 'WB',
       'Paramount', 'STX Entertainment', 'Lionsgate Films',
       'Walt Disney Animation Studios', 'Buena Vista Distribution Compa',
       'IFC Films', 'Lionsgate'],
      dtype='object', name='studio')

In [161]:
#studio_names_replace = {"fresh":1, "rotten":0}
#sorting_studios = freshness_df["fresh"].replace(freshness_replace, inplace=True)

#Remember, positivereviewsratingsdf is the DF that contains production companies with 147 or more positive reviews. "Popular"
is_fresh = [1]
popular_and_fresh = positive_reviews_ratings_df.loc[positive_reviews_ratings_df["fresh"].isin(is_fresh)]


In [162]:
popular_and_fresh

id Rated                                              genre  \
243       8    PG                              Drama|Kids and Family   
244       8    PG                              Drama|Kids and Family   
245       8    PG                              Drama|Kids and Family   
246       8    PG                              Drama|Kids and Family   
249       8    PG                              Drama|Kids and Family   
...     ...   ...                                                ...   
54420  2000     R  Action and Adventure|Art House and Internation...   
54422  2000     R  Action and Adventure|Art House and Internation...   
54425  2000     R  Action and Adventure|Art House and Internation...   
54427  2000     R  Action and Adventure|Art House and Internation...   
54431  2000     R  Action and Adventure|Art House and Internation...   

          director                 studio  \
243    Jay Russell  Warner Bros. Pictures   
244    Jay Russell  Warner Bros. Pictures   
245    Jay Russell  Warner Bros. Pictures   
246    Jay Russell  Warner Bros. Pictures   
249    Jay Russell  Warner Bros. Pictures   
...            ...                    ...   
54420          NaN      Columbia Pictures   
54422          NaN      Columbia Pictures   
54425          NaN      Columbia Pictures   
54427          NaN      Columbia Pictures   
54431          NaN      Columbia Pictures   

                                                  review Rating  fresh  \
243    Great boy-and-dog tale, but be prepared for te...    4/5      1   
244    Not a mawkish dying-dog tearjerker, "My Dog Sk...  3.5/4      1   
245    Features two irresistible lead characters -- a...  2.5/4      1   
246              A heart-affecting boy-with-a-dog drama.    NaN      1   
249    I had shelved a movie critic's usual reserve a...    3/4      1   
...                                                  ...    ...    ...   
54420  The spaniel-eyed Jean Reno infuses Hubert with...    3/4      1   
54422  Arguably the best script that Besson has writt...  3.5/5      1   
54425  Despite Besson's high-profile name being Wasab...    NaN      1   
54427  The real charm of this trifle is the deadpan c...    NaN      1   
54431                                                NaN    3/5      1   

                critic  
243         Nell Minow  
244        Nick Rogers  
245     Judith Egerton  
246                NaN  
249        Roger Ebert  
...                ...  
54420     Megan Turner  
54422       Wade Major  
54425       Andy Klein  
54427    Laura Sinagra  
54431  Nicolas Lacroix  

[19010 rows x 9 columns]

The goal currently is to figure out which companies are getting not only the best reviews, but a lot of them. Virality now a days is a very important component to film success. We want consumers to be talking about the film, so production companies that made movies that only have one or two positive reviews are not going to do us much justice.

In [163]:
popular_and_fresh["studio"].value_counts()

Universal Pictures                         2373
Paramount Pictures                         1760
Sony Pictures Classics                     1586
Warner Bros. Pictures                      1157
Sony Pictures                              1133
20th Century Fox                           1008
The Weinstein Company                       939
Fox Searchlight Pictures                    802
Focus Features                              611
Walt Disney Pictures                        569
Miramax Films                               550
MGM                                         501
Columbia Pictures                           450
Paramount Vantage                           429
New Line Cinema                             402
Warner Bros.                                399
Roadside Attractions                        357
Newmarket Film Group                        350
Lions Gate Films                            289
Fox Searchlight                             263
Buena Vista Pictures                    

In [174]:
popular_and_fresh["studio"].value_counts()[:10]

Universal Pictures          2563
Paramount Pictures          1924
Warner Bros. Pictures       1722
Sony Pictures Classics      1586
Sony Pictures               1133
20th Century Fox            1008
The Weinstein Company        939
Fox Searchlight Pictures     802
Focus Features               611
Lionsgate                    601
Name: studio, dtype: int64

In [185]:
most_popular_movies = popular_and_fresh["studio"].value_counts().index
most_popular_movies

#make a diagram showing correlation between the amount of ratings, and average freshness score


Index(['Universal Pictures', 'Paramount Pictures', 'Warner Bros. Pictures',
       'Sony Pictures Classics', 'Sony Pictures', '20th Century Fox',
       'The Weinstein Company', 'Fox Searchlight Pictures', 'Focus Features',
       'Lionsgate', 'Walt Disney Pictures', 'Miramax Films', 'MGM',
       'Columbia Pictures', 'Paramount Vantage', 'New Line Cinema',
       'A24 Films', 'Roadside Attractions', 'Newmarket Film Group',
       'Fox Searchlight', 'Buena Vista Pictures', 'DreamWorks SKG',
       'Fingerprint Releasing / Bleecker Street', 'USA Films',
       'Summit Entertainment', 'Dimension Films', 'STX Entertainment',
       'Walt Disney Animation Studios', 'Buena Vista Distribution Compa',
       'IFC Films'],
      dtype='object')

Our popular and fresh dataframe has narrowed down the companies to focus on with minimal studio name cleaning needed. 

In [169]:
#DUPLICATES: warner bros vs warner bros pictures? Paramount and paramount pictures for sure. a24. lionsgate vs Lions Gate, universal vs universal pictures

studio_names_replace = {"Lions Gate Films":"Lionsgate", "Lionsgate Films":"Lionsgate", "A24": "A24 Films", "WB": "Warner Bros. Pictures", "Warner Bros.": "Warner Bros. Pictures",
                       "Paramount": "Paramount Pictures", "Universal": "Universal Pictures"}
cleaning_studios_method = popular_and_fresh["studio"].replace(studio_names_replace, inplace=True)

C:\Users\saman\anaconda3\envs\learn-env\lib\site-packages\pandas\core\series.py:4563: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


In [171]:
popular_and_fresh["studio"].value_counts()

Universal Pictures                         2563
Paramount Pictures                         1924
Warner Bros. Pictures                      1722
Sony Pictures Classics                     1586
Sony Pictures                              1133
20th Century Fox                           1008
The Weinstein Company                       939
Fox Searchlight Pictures                    802
Focus Features                              611
Lionsgate                                   601
Walt Disney Pictures                        569
Miramax Films                               550
MGM                                         501
Columbia Pictures                           450
Paramount Vantage                           429
New Line Cinema                             402
A24 Films                                   366
Roadside Attractions                        357
Newmarket Film Group                        350
Fox Searchlight                             263
Buena Vista Pictures                    

Cleaning up the studios did not change the amount of entries drastically but it will be easier for us to measure success with no duplicates!

In [182]:
popular_and_fresh["Rating"].value_counts()[:50]

3/4       2239
4/5       1887
3/5       1780
3.5/4     1151
3.5/5      845
2.5/4      778
B          725
4/4        632
5/5        579
B+         540
B-         491
4.5/5      382
A-         341
8/10       327
7/10       278
A          259
6/10       190
9/10       189
1           82
2.5/5       71
8           62
C+          58
7           40
7.5/10      40
2/4         39
A+          38
8.5/10      35
9           16
6.5/10      16
3.0/4       16
9.5/10      13
3.5         13
3           12
2/5         12
3.0/5       10
C           10
4.0/4       10
5.0/5        8
5/10         8
3/6          7
4.0/5        6
2.1/2        6
4/6          6
7.1/10       5
6            5
5            5
4            5
3.7          4
R            4
2.7          4
Name: Rating, dtype: int64

I think if I convert all the letter ratings to a number first, I will be able to convert the rest of these ratings... somehow.... into percentages

In [ ]:
letter_grade_conversion = {"B":"", "B+": "", "B-": "", "A-": "", "A": "", "C+": "", "A+": "", "C": ""}
#cleaning_grades_method = popular_and_fresh["studio"].replace(studio_names_replace, inplace=True)

In [ ]:
popular_and_fresh